### ISSUE TITLE
Squeeze function error

### ISSUE THREAD

**Issue by mhsamavatian** [weinman/cnn_lstm_ctc_ocr#33]
there is no access tp mjsynth dataset. How can I train the model with IAM dataset?

**Comment by weinman** [comment]
Can you explain what you mean by "there is no access to mjsynth dataset"? To download it, follow the [training instructions](https://github.com/weinman/cnn_lstm_ctc_ocr/#training).

To train the model on your own dataset, you need to generate image, label pairs for your data (e.g., tensors and sparse tensors) and connect them in whatever way seems suitable (e.g., placeholder+feed dict, TFRecord files of Examples, etc.) within a variant of `train.py`.

I'll be merging an update of the code that uses the Dataset API and the Estimator framework soon, with a more generalized input pipeline. That won't solve your problems directly, but it may give some additional flexibility that could ease the process of adapting to other data/tasks.

**Comment by weinman** [comment]
The image width can vary, but the code assumes the image height is exactly 32, so that after the four levels of vertical max-pooling, the height ends up being one. 

The data order of the `inputs` tensor coming into `model.convnet_layers` should be NHWC. (batch size, height, width, channels). The raw mjsynth data was 31 pixels high, but preprocessing in `mjsynth.py` repeats a row to make it an "even" 32 pixels. 

It's not a mistake in the comment. Whereas the default batch in `train.py` is also 32, it may be that the dynamic shape reported to you has inferred the fixed batch size but not the image size. 

If you have a fixed image height but of a value other than 32, you could try a different strategy for collapsing data vertically (e.g., adjust the `pool8` layer op). If your data is not height normalized (or not height normalizable), you'll have to get even more creative.

The primary reason for cutting off the minimum width in the script that processes Examples for the TFRecord files is that there are plenty of images in the mjsynth dataset that do not have enough pixels in width to compensate for the horizontal data pooling (leaving a feature sequence that's shorter than the label sequence, which CTC can't process).
