### ISSUE TITLE
Train on vertical patches

### ISSUE THREAD

**Issue by lijo381** [weinman/cnn_lstm_ctc_ocr#64]
I am trying to predict text from vertical images, where patch height is greater than width and the texts are arranged one below the other. Since the network is trained for horizontal text patches what changes do i need to make to get predictions on these kind of images??

**Comment by weinman** [comment]
Probably the most pain-free method would be to simply rotate your input images by -90º for both training and testing; assuming your training labels are arranged sequentially from top-to-bottom, the model should learn to read the  top-to-bottom this as left-to-right in the actual (rotated) images.

Otherwise you'll be exchanging rows and columns throughout the model code
